---
- name: update apt cache
  apt: update_cache=yes
- name: install required packages using apt-get
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - git-core
    - vim
    - build-essential
    - python3
    - python3-dev
    - python3-setuptools
    - python3-matplotlib
    - python3-numpy
    - python3-scipy
    - python3-pandas
    - python3-pil
    - idle3
- name: set default vagrant ssh directory
  lineinfile: dest=/home/vagrant/.bashrc line="cd /vagrant/code"
  tags:
    - set_default_dir
- name: set $DISPLAY environment variable
  lineinfile: dest=/home/vagrant/.bashrc line="export DISPLAY=:0.0"
